"""
config.py — Shared settings for both backend and frontend.
Only edit GROQ_API_KEY and TESSERACT_PATH before running.
"""

import os

# ── Groq API ──────────────────────────────────────────────────────────────────
# Get free key at: https://console.groq.com
# Set GROQ_API_KEY in your environment or copy this file to config.py and add it locally.
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
GROQ_MODEL   = "llama-3.3-70b-versatile"       # fast, free, highly capable

# ── Backend URL (FastAPI) ─────────────────────────────────────────────────────
API_BASE_URL = "http://localhost:8000"

# ── Dataset ───────────────────────────────────────────────────────────────────
DATASET_PATH = "data/ai_jobs_market_2025_2026.csv"

# ── Tesseract (for scanned PDF OCR) ──────────────────────────────────────────
# Windows → r"C:\Program Files\Tesseract-OCR\tesseract.exe"
# Mac     → r"/usr/local/bin/tesseract"
# Linux   → r"/usr/bin/tesseract"
TESSERACT_PATH = r"C:\Program Files\Tesseract-OCR\tesseract.exe"

# ── PDF Branding ──────────────────────────────────────────────────────────────
REPORT_TITLE  = "Career Roadmap Report"
REPORT_FOOTER = "Generated by AI Career Co-Pilot"

# ── Languages ─────────────────────────────────────────────────────────────────
LANGUAGES = {
    "English":            "en",
    "Hindi":              "hi",
    "Telugu":             "te",
    "Tamil":              "ta",
    "Kannada":            "kn",
    "Malayalam":          "ml",
    "Marathi":            "mr",
    "Bengali":            "bn",
    "Gujarati":           "gu",
    "Punjabi":            "pa",
    "Urdu":               "ur",
    "French":             "fr",
    "German":             "de",
    "Spanish":            "es",
    "Arabic":             "ar",
    "Chinese Simplified": "zh",
    "Japanese":           "ja",
}

# ── India locations (for Naukri link) ─────────────────────────────────────────
INDIA_LOCATIONS = [
    "india", "hyderabad", "bangalore", "bengaluru", "mumbai", "delhi",
    "chennai", "pune", "kolkata", "ahmedabad", "jaipur", "surat",
    "lucknow", "kochi", "chandigarh", "noida", "gurgaon", "gurugram",
    "indore", "bhopal", "vizag", "visakhapatnam", "nagpur", "coimbatore",
]
