"""
config.example.py — Example config file for AI Career Guidance System.
Copy this to config.py and add your own secret values locally.
"""

# ── Groq API ──────────────────────────────────────────────────────────────────
# Get free key at: https://console.groq.com
GROQ_API_KEY = "your-groq-api-key-here"
GROQ_MODEL   = "llama-3.3-70b-versatile"

# ── Backend URL (FastAPI) ─────────────────────────────────────────────────────
API_BASE_URL = "http://localhost:8000"

# ── Dataset ───────────────────────────────────────────────────────────────────
DATASET_PATH = "data/ai_jobs_market_2025_2026.csv"

# ── Tesseract (for scanned PDF OCR) ──────────────────────────────────────────
# Windows → r"C:\Program Files\Tesseract-OCR\tesseract.exe"
TESSERACT_PATH = r"C:\Program Files\Tesseract-OCR\tesseract.exe"

# ── PDF Branding ──────────────────────────────────────────────────────────────
REPORT_TITLE  = "Career Roadmap Report"
REPORT_FOOTER = "Generated by AI Career Co-Pilot"
